### ISSUE TITLE
Align with Spring Boot's recommendations for naming third-party starters

### ISSUE THREAD

**Issue by wilkinsona** [nkonev/r2dbc-migrate#1]
Thanks for creating this project and being part of the Spring community.

Spring Boot's reference documentation contains [some guidelines](https://docs.spring.io/spring-boot/docs/2.2.6.RELEASE/reference/htmlsingle/#using-boot-starter) on naming third-party starters. We prefer to reserve `spring-boot-starter-` for Spring Boot's own starters and for third party starters to use a `-spring-boot-starter` suffix instead.

Could you please rename your starter to `r2dbc-migrate-spring-boot-starter`?

**Comment by nkonev** [comment]
Fixed in 0.0.24

**Comment by wilkinsona** [comment]
Thank you.
