### ISSUE TITLE
Cannot use r2dbc.migrate with spring.sql.init

### ISSUE THREAD

**Issue by wickedev** [nkonev/r2dbc-migrate#15]
## Issue

I want to apply the initial schema using `spring.sql.init` on `application.yml` and then use `r2dbc.migrate` to do the migration. However, the default behavior is that `R2dbcMigrateAutoConfiguration.R2dbcMigrateBlockingInvoker` bean is initialized first, and then `SqlR2dbcScriptDatabaseInitializer` is initialized later. The call order is reversed and the application crashes.

[application.yml](https://github.com/lingomate/server/blob/83481d4f24c42498d5f515b84447eec8a4f1f286/src/main/resources/application.yml#L14)
```yml

spring:
  sql:
    init:
      enabled: true
      mode: always
      schemaLocations: classpath:/db/schema.sql

r2dbc:
  migrate:
    resourcesPath: classpath:/db/migration/*.sql
```

```sql
# schema.sql
-- users
CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(191) UNIQUE NOT NULL,
    name VARCHAR(191),
    hash_salt VARCHAR(500) NOT NULL,
    roles VARCHAR(16)[]
);
```

```sql
# V2__alter_deleted_at_field_on_users,nontransactional.sql
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
```

```sh
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42P01] relation "users" does not exist
```

## Temp Solution

When initializing `R2dbcMigrateBlockingInvoker`, it tells `SqlR2dbcScriptDatabaseInitializer` that it needs a dependency (I don't know if this is best) so that `SqlR2dbcScriptDatabaseInitializer` is called first and `R2dbcMigrateBlockingInvoker` is called later. I also tried using `@DependOn` or `@AutoConfigureAfter` but it didn't work well.

[repository](https://github.com/lingomate/server/tree/83481d4f24c42498d5f515b84447eec8a4f1f286)

```kotlin
@SpringBootApplication(exclude = [R2dbcMigrateAutoConfiguration::class])
class Application

@Configuration(proxyBeanMethods = false)
@EnableConfigurationProperties(SpringBootR2dbcMigrateProperties::class)
class DatabaseConfiguration {

    @Bean(name = ["ar2dbcMigrate"], initMethod = "migrate")
    fun r2dbcMigrate(
        connectionFactory: ConnectionFactory,
        properties: SpringBootR2dbcMigrateProperties,
        @Autowired(required = false) maybeUserDialect: SqlQueries?,
        @Autowired(required = false) initializer: SqlR2dbcScriptDatabaseInitializer? // <--- THIS
    ): R2dbcMigrateAutoConfiguration.R2dbcMigrateBlockingInvoker {
        return R2dbcMigrateAutoConfiguration.R2dbcMigrateBlockingInvoker(
            connectionFactory,
            properties,
            maybeUserDialect
        )
    }
}
```

## Expect

`r2dbc.migrate` and `spring.sql.init` to be used together by having `SqlR2dbcScriptDatabaseInitializer` called first and then `R2dbcMigrateBlockingInvoker`.

Thank you for your awesome project.

**Comment by nkonev** [comment]
I've done by [different way](https://github.com/nkonev/r2dbc-migrate/blob/84b15e170865e5be445f594b599fffd517817e82/r2dbc-migrate-spring-boot-starter/src/main/java/name/nkonev/r2dbc/migrate/autoconfigure/R2dbcMigrateAutoConfiguration.java#L50), thy 1.8.1 when it will be available at [Maven Central](https://repo.maven.apache.org/maven2/name/nkonev/r2dbc-migrate/r2dbc-migrate-spring-boot-starter/1.8.1/)
