### ISSUE TITLE
Spring Framework 6 / Boot 3 support

### ISSUE THREAD

**Issue by vladimirfx** [nkonev/r2dbc-migrate#23]
Spring Boot 3 at RC phase. Unfortunately R2DBC Migrate broken because of use R2BC 1.0 SPI etc in Spring Framework 6. I've try locally update dependency and it seems to work with supported drivers. May be release some milestone artifact based on Spring Boot 3 for testing and provide valuable feedback to Spring team?

**Comment by nkonev** [comment]
I've just released 2.8.0-RC1
* Java 17 required
* Only PostgreSQL and SQL Server drivers are tested at time of writing. MySQL driver looks abandoned, MariaDB still isn't upgraded to R2DBC 1.0

**Comment by rjaros** [comment]
Could you please release the 2.8.0 final?

**Comment by nkonev** [comment]
Don, the version will appear in the Maven Central after a while
