### ISSUE TITLE
Releases Notes

### ISSUE THREAD

**Issue by seljabali** [nkonev/r2dbc-migrate#29]
Hi @nkonev 👋 

Thank you so much for your project. It's much appreciated.

Is it possible to create Github releases along side them release notes? 

Release notes documenting what has been added/changed may help those using to project anticipate any follow up work needed on their end.

For example I'm not sure what has just changed between 2.9.4 to 2.10.0 and if that's going to impact our project.

Thanks.

**Comment by nkonev** [comment]
Hi!

Until it isn't done 
you can use GitHub's compare feature
https://github.com/nkonev/r2dbc-migrate/compare/2.9.4...2.10.0

**Comment by seljabali** [comment]
Sounds good @nkonev! Thank you so much for what you do.
