### ISSUE TITLE
Parse migration version as a long value instead of int

### ISSUE THREAD

**Issue by V-Nikolenko** [nkonev/r2dbc-migrate#30]
Hi! I'm thrilled to use this library in my project, but unfortunately, it does not support migration versions with the long type.

I'm using the '[Flyway Migration Creation](https://plugins.jetbrains.com/plugin/8597-flyway-migration-creation)' IntelliJ IDE plugin, which creates files as follows:
```
V20240309222903__create_new_example_table.sql
V20240309222927__insert_initial_example_data.sql
```

When I run the application, it throws a NumberFormatException because it cannot parse this long value as an int in name.nkonev.r2dbc.migrate.core.FilenameParser#getVersion. Could you please take a look at it?

Thanks in advance!

**Comment by nkonev** [comment]
Just released 2.12.0, it should be available after some time. It's recommended (but it still works for low numbers without this change at least in case PostgreSQL) to make `id` column `bigint`.
