### ISSUE TITLE
Support for H2

### ISSUE THREAD

**Issue by PauloPortfolio** [nkonev/r2dbc-migrate#4]
Hello,

First of all, your lib is amazing -> Wonderful job.

I would like to suggest add support to H2 because this is focused in tests/TDD, than PostgreSQL, Microsoft SQL Server, MySQL(although those are useful for test as well).

Thanks

**Comment by nkonev** [comment]
@PauloPortfolio 

I've created 1.0.8 with initial H2 support.
It will be available at [Maven Central](https://repo.maven.apache.org/maven2/name/nkonev/r2dbc-migrate/r2dbc-migrate-spring-boot-starter/) soon.

By the way I haven't tested it with H2 compatibility modes. (H2 as MySQL, H2 as Postgres and so on...).
