### ISSUE TITLE
Special character are not allowed in  the migration scripts

### ISSUE THREAD

**Issue by PauloPortfolio** [nkonev/r2dbc-migrate#7]
0) GitHub project link related with the error that causes this issue: https://github.com/PauloPortfolio/springwebflux-tdd-devdojo 

1) The Special character "$" are not being accepted for the migration process.

2) For example: This INSERT statement is completely normal, and it is normal processed for the r2dbc-migrate BECAUSE we have a 'plaintext' password (DEVDOJO):
INSERT INTO userspasswords 
          (nameuser, username, password, authorities)
VALUES ('demetria',
        'demetria',
        'devdojo',
        'ROLE_USER');

3) HOWEVER, when I change the field 'PASSWORD' from PLAIN-TEXT 'DEVDOJO' 
to ENCRYTED PASSWORD 'DEVDOJO' ({bcrypt}$2a$10$lBm1Qy45bR/fNT5i5OUBseNPcONtZs10earjLZ773qq.byhK/yKmS), the specials characteres are not allowed, specially "$", for instance:
INSERT INTO userspasswords 
          (nameuser, username, password, authorities)
VALUES ('demetria',
        'demetria',
        '{bcrypt}$2a$10$lBm1Qy45bR/fNT5i5OUBseNPcONtZs10earjLZ773qq.byhK/yKmS',
        'ROLE_USER');

         THIS FINAL ERROR HAPPENS:------------------------>>>
 By 'Writing metadata version 3' 1 rows updated
web-api_1     | 2020-08-04 20:54:43.971  INFO 7 --- [tor-tcp-epoll-1] n.n.r2dbc.migrate.core.R2dbcMigrate      : Applying MigrationInfo{version=4, description='insert in table userpasswords', splitByLine=false, transactional=true}
web-api_1     | 2020-08-04 20:54:43.977  INFO 7 --- [tor-tcp-epoll-1] n.n.r2dbc.migrate.core.R2dbcMigrate      : By 'Releasing lock after error' 1 rows updated
web-api_1     | 2020-08-04 20:54:43.980  WARN 7 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'animeController': Unsatisfied dependency expressed through field 'service'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'animeService': Unsatisfied dependency expressed through field 'repo'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'animeRepository' defined in academy.devdojo.webflux.repository.AnimeRepository defined in @EnableR2dbcRepositories declared on R2dbcRepositoriesAutoConfigureRegistrar.EnableR2dbcRepositoriesConfiguration: Cannot resolve reference to bean 'r2dbcDatabaseClient' while setting bean property 'databaseClient'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcMigrate' defined in class path resource [name/nkonev/r2dbc/migrate/autoconfigure/R2dbcMigrateAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Statement 'INSERT INTO userspasswords (nameuser, username, password, authorities)
web-api_1     | VALUES ('paulo',
web-api_1     |         'paulo',
web-api_1     |         '{bcrypt}$2a$10$lBm1Qy45bR/fNT5i5OUBseNPcONtZs10earjLZ773qq.byhK/yKmS',
web-api_1     |         'ROLE_ADMIN,ROLE_USER');
web-api_1     |
web-api_1     | INSERT INTO userspasswords (nameuser, username, password, authorities)
web-api_1     | VALUES ('demetria',
web-api_1     |         'demetria',
web-api_1     |         'devdojo',
web-api_1     |         'ROLE_USER');' cannot be created. This is often due to the presence of both multiple statements and parameters at the same time.
web-api_1     | 2020-08-04 20:54:43.991  INFO 7 --- [           main] ConditionEvaluationReportLoggingListener :
web-api_1     |
web-api_1     | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
web-api_1     | 2020-08-04 20:54:43.996 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed

**Comment by nkonev** [comment]
@PauloPortfolio 
Link is not available:
![Screenshot_20200805-001029](https://user-images.githubusercontent.com/3160384/89345608-67115a00-d6b0-11ea-8637-87270aca160d.jpg)

**Comment by nkonev** [comment]
Do you use Postgresql ?

**Comment by PauloPortfolio** [comment]
> 
> 
> @PauloPortfolio
> Link is not available:
> ![Screenshot_20200805-001029](https://user-images.githubusercontent.com/3160384/89345608-67115a00-d6b0-11ea-8637-87270aca160d.jpg)

Sorry, the repository is public now.

**Comment by PauloPortfolio** [comment]
> 
> 
> Do you use Postgresql ?

Yep, I am using Postgres.

**Comment by nkonev** [comment]
@PauloPortfolio 
This library doesn't do any assumptions about migration files content.
See at driver's [page](https://github.com/pgjdbc/r2dbc-postgresql):
> PostgreSQL uses index parameters that are prefixed with $.

You need to escape your special symbols. Check [here](https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS).

I've created [commit](https://github.com/nkonev/r2dbc-migrate-example/commit/dc8b83f4cd658f0905cfb3b5cd902d6cd7b5f085) in my example. Its output:
```
2020-08-05 01:21:44.760  INFO 98000 --- [           main] n.n.r.m.example.CustomerApplication      : === Print all customers ===
2020-08-05 01:21:44.783  INFO 98000 --- [tor-tcp-epoll-6] n.n.r.m.example.CustomerApplication      : Output: Customer{id=1, firstName='Test Customer Name 1', lastName='Test Customer Surname 1'}
2020-08-05 01:21:44.794  INFO 98000 --- [tor-tcp-epoll-6] n.n.r.m.example.CustomerApplication      : Output: Customer{id=2, firstName='Funny User Name 2', lastName='Funny User Surname 2'}
2020-08-05 01:21:44.795  INFO 98000 --- [tor-tcp-epoll-6] n.n.r.m.example.CustomerApplication      : Output: Customer{id=3, firstName='Name with $', lastName='Escape example 1'}
2020-08-05 01:21:44.795  INFO 98000 --- [tor-tcp-epoll-6] n.n.r.m.example.CustomerApplication      : Output: Customer{id=4, firstName='Pokemon for 5 $.', lastName='See more examples at https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS'}
```

**Comment by nkonev** [comment]
Update
 it seems doesn't working.

**Comment by nkonev** [comment]
@PauloPortfolio 
I've created workaround [example](https://github.com/nkonev/r2dbc-migrate-example/commit/fdda853a3b77104dd37f135dfcd9593c5766a58c) with Unicode-escaped string. `U&` and `0024` instead $1.

Its output:
```
2020-08-05 02:32:05.618  INFO 107944 --- [tor-tcp-epoll-2] n.n.r.m.example.CustomerApplication      : Output: Customer{id=5, firstName='{bcrypt}$2a$10$lBm1Qy45bR/fNT5i5OUBseNPcONtZs10earjLZ773qq.byhK/yKmS', lastName='Unicode escape as workaround'}
```

Seems problem is [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/16925b51775960a95209bba83e1ec976406e182c/src/main/java/io/r2dbc/postgresql/SimpleQueryPostgresqlStatement.java#L139).
Please [create issue](https://github.com/pgjdbc/r2dbc-postgresql/issues/new/choose) in r2dbc-postgresql.

**Comment by nkonev** [comment]
https://github.com/pgjdbc/r2dbc-postgresql/issues/312
